# Set all versions
LLUVIA_BUILD_TYPE ?= UNOFFICIAL

LLUVIA_DATE_YEAR := $(shell date -u +%Y)
LLUVIA_DATE_MONTH := $(shell date -u +%m)
LLUVIA_DATE_DAY := $(shell date -u +%d)
LLUVIA_DATE_HOUR := $(shell date -u +%H)
LLUVIA_DATE_MINUTE := $(shell date -u +%M)
LLUVIA_BUILD_DATE_UTC := $(shell date -d '$(LLUVIA_DATE_YEAR)-$(LLUVIA_DATE_MONTH)-$(LLUVIA_DATE_DAY) $(LLUVIA_DATE_HOUR):$(LLUVIA_DATE_MINUTE) UTC' +%s)
LLUVIA_BUILD_DATE := $(LLUVIA_DATE_YEAR)$(LLUVIA_DATE_MONTH)$(LLUVIA_DATE_DAY)-$(LLUVIA_DATE_HOUR)$(LLUVIA_DATE_MINUTE)

LLUVIA_PLATFORM_VERSION := 10.0

TARGET_PRODUCT_SHORT := $(subst lluvia_,,$(LLUVIA_BUILD))

LLUVIA_VERSION := LLuviaOS_$(LLUVIA_BUILD)-$(LLUVIA_PLATFORM_VERSION)-$(LLUVIA_BUILD_DATE)-$(LLUVIA_BUILD_TYPE)
LLUVIA_VERSION_PROP := 4.1
ROM_FINGERPRINT := LLuviaOS/$(LLUVIA_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(LLUVIA_BUILD_DATE)

LLUVIA_PROPERTIES := \
    org.lluvia.version=$(LLUVIA_VERSION_PROP) \
    org.lluvia.build_date=$(LLUVIA_BUILD_DATE) \
    org.lluvia.build_date_utc=$(LLUVIA_BUILD_DATE_UTC) \
    org.lluvia.build_type=$(LLUVIA_BUILD_TYPE) \
    org.lluvia.fingerprint=$(ROM_FINGERPRINT)
